spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
  datasource:
    driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
    url: jdbc:TAOS-RS://localhost:6041/test?charset=UTF-8&locale=en_US.UTF-8&timezone=UTC-8
    username: root
    password: taosdata

    druid:
      initial-size: 5
      min-idle: 5
      max-active: 5

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    com:
      taosdata:
        example:
          mybatisplusdemo:
            mapper: debug